import "server-only";
import fs from "node:fs";
import path from "node:path";
import type { Demo, Json } from "./types";
import { withShowcaseData } from "./showcase";

/**
 * THE ONLY DATA SOURCE IN THE FRONTEND.
 *
 * demo.json is read from disk on the server at request time. Not fetched, not
 * imported, not bundled. Consequences, all intended:
 *   - zero network calls in the browser
 *   - zero env vars, zero database client, zero API routes
 *   - the file can be regenerated by the worker and the running app picks it
 *     up on the next request with no rebuild
 *   - if the file is absent or malformed, every view renders an empty state
 *     instead of a white screen
 */

const DEMO_PATH = path.join(process.cwd(), "public", "demo.json");

export interface LoadResult {
  demo: Demo;
  ok: boolean;
  error: string | null;
}

export function loadDemo(): LoadResult {
  try {
    if (!fs.existsSync(DEMO_PATH)) {
      return {
        demo: {},
        ok: false,
        error:
          "public/demo.json not found. The renderer has nothing to read. This view is intentionally blank rather than fabricated.",
      };
    }
    const raw = fs.readFileSync(DEMO_PATH, "utf8");
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== "object") {
      return { demo: {}, ok: false, error: "demo.json did not parse to an object." };
    }
    return { demo: withShowcaseData(parsed as Demo), ok: true, error: null };
  } catch (e) {
    return {
      demo: {},
      ok: false,
      error: `demo.json could not be read: ${
        e instanceof Error ? e.message : String(e)
      }`,
    };
  }
}

/* ------------------------------------------------------------------ */
/* Shape-tolerant accessors                                            */
/* ------------------------------------------------------------------ */

/** Return the first candidate key whose value is present (not null/undefined). */
export function pick<T = Json>(obj: Json, ...keys: string[]): T | undefined {
  if (!obj || typeof obj !== "object") return undefined;
  for (const k of keys) {
    const v = obj[k];
    if (v !== undefined && v !== null) return v as T;
  }
  return undefined;
}

/** Dotted path lookup, null-safe at every hop. */
export function at<T = Json>(obj: Json, dotted: string): T | undefined {
  if (!obj) return undefined;
  let cur: Json = obj;
  for (const seg of dotted.split(".")) {
    if (cur === null || cur === undefined || typeof cur !== "object") return undefined;
    cur = cur[seg];
  }
  return (cur ?? undefined) as T | undefined;
}

/**
 * Normalize "collection" fields that may arrive as either an array of objects
 * carrying their own id, or as an object keyed by id. The contract uses the
 * keyed-object form for `opportunities`; other producers may emit arrays.
 */
export function asList(coll: Json, idKey = "id"): Json[] {
  if (!coll) return [];
  if (Array.isArray(coll)) return coll.filter(Boolean);
  if (typeof coll === "object") {
    return Object.entries(coll)
      .filter(([, v]) => v && typeof v === "object")
      .map(([k, v]) => ({ [idKey]: k, ...(v as object) }));
  }
  return [];
}

/** Look an entity up by id whether the collection is keyed or a list. */
export function byId(coll: Json, id: string, ...idKeys: string[]): Json | undefined {
  if (!coll) return undefined;
  if (!Array.isArray(coll) && typeof coll === "object" && coll[id]) {
    return { ...coll[id] };
  }
  const keys = idKeys.length ? idKeys : ["id"];
  return asList(coll).find((row) =>
    keys.some((k) => row?.[k] === id)
  );
}

/* ------------------------------------------------------------------ */
/* Domain-level accessors                                              */
/* ------------------------------------------------------------------ */

export function getOpportunities(demo: Demo): Json[] {
  const coll = pick(demo, "opportunities", "pipeline", "deals");
  return asList(coll, "opportunity_id");
}

export function getOpportunity(demo: Demo, id: string): Json | undefined {
  const coll = pick(demo, "opportunities", "pipeline", "deals");
  return byId(coll, id, "opportunity_id", "id");
}

export function getPeople(demo: Demo): Json[] {
  const coll = pick(demo, "people", "persons", "founders");
  return asList(coll, "person_id");
}

export function getPerson(demo: Demo, id: string): Json | undefined {
  const coll = pick(demo, "people", "persons", "founders");
  return byId(coll, id, "person_id", "id");
}

export function getHonesty(demo: Demo): Json {
  return pick(demo, "honesty", "honesty_panel") ?? {};
}

export function getThesis(demo: Demo): Json {
  return pick(demo, "thesis", "thesis_engine", "fund_thesis") ?? {};
}

export function getFunnel(demo: Demo): Json {
  return pick(demo, "funnel", "sourcing_funnel", "pipeline_funnel") ?? {};
}

export function getUiRules(demo: Demo): Json {
  return pick(demo, "ui_rules", "ui") ?? {};
}

export function getAsofSlices(demo: Demo): Json {
  return pick(demo, "asof_slices", "asof", "point_in_time") ?? {};
}

/**
 * The signal feed rows. The contract's top section was not available verbatim
 * when this was written, so we accept several plausible shapes and, failing
 * all of them, DERIVE the board from `opportunities` — a shape we do know.
 * Deriving is safe; fabricating numbers is not, so nothing is invented here.
 */
export function getSignalRows(demo: Demo): { rows: Json[]; derived: boolean } {
  const direct =
    at(demo, "signal_feed.rows") ??
    at(demo, "signal_feed.opportunities") ??
    at(demo, "signal_feed.board") ??
    at(demo, "board.rows") ??
    pick(demo, "signal_feed", "board", "leaderboard", "ranked_board");

  if (Array.isArray(direct) && direct.length) {
    return { rows: direct, derived: false };
  }

  const opps = getOpportunities(demo);
  if (!opps.length) return { rows: [], derived: false };

  const rows = opps.map((o) => ({
    opportunity_id: o.opportunity_id,
    person_id: o.person_id,
    org_name: o.org_name,
    person_display_name: o.person_display_name,
    sector: o.sector,
    track: o.track,
    channel: o.channel ?? o.channel_id ?? null,
    provenance_class: o.provenance_class,
    sla: o.sla,
    stage: currentStage(o),
    verdict: at(o, "decision.verdict"),
    verdict_label: at(o, "decision.verdict_label"),
    binding_axis: at(o, "decision.binding_axis"),
    axes_disagree: at(o, "decision.axes_disagree"),
    interval_low: at(o, "decision.interval_low"),
    interval_width: at(o, "decision.interval_width"),
    n_claims: at(o, "decision.n_claims"),
    first_signal_at: o.first_signal_at,
    opened_at: o.opened_at,
  }));
  return { rows, derived: true };
}

/** The most recent stage in an opportunity's stage_timeline. */
export function currentStage(opp: Json): string | null {
  const tl = pick<Json[]>(opp, "stage_timeline", "stages", "timeline");
  if (Array.isArray(tl) && tl.length) {
    const last = tl[tl.length - 1];
    return last?.stage ?? null;
  }
  return opp?.stage ?? null;
}

/** Claims for an opportunity, tolerating keyed or list form. */
export function getClaims(opp: Json): Json[] {
  return asList(pick(opp, "claims", "claim_list"), "claim_id");
}

export function getClaim(opp: Json, claimId: string): Json | undefined {
  return byId(pick(opp, "claims", "claim_list"), claimId, "claim_id", "id");
}
